export const CountryFlags = [
  {'Name': 'afghanistan', 'Country': 'Afghanistan (+93)', 'CountryCode': '+93'},
  {'Name': 'albania', 'Country': 'Albania (+355)', 'CountryCode': '+355'},
  {'Name': 'algeria', 'Country': 'Algeria (+213)', 'CountryCode': '+213'},
  {'Name': 'american-samoa', 'Country': 'American Samoa (+1-684)', 'CountryCode': '+1-684'},
  {'Name': 'andorra', 'Country': 'Andorra (+376)', 'CountryCode': '+376'},
  {'Name': 'angola', 'Country': 'Angola (+244)', 'CountryCode': '+244'},
  {'Name': 'anguilla', 'Country': 'Anguilla (+1-264)', 'CountryCode': '+1-264'},
  {'Name': 'antarctica', 'Country': 'Antarctica (+672)', 'CountryCode': '+672'},
  {'Name': 'antigua-and-barbuda', 'Country': 'Antigua and Barbuda (+1-268)', 'CountryCode': '+1-268'},
  {'Name': 'argentina', 'Country': 'Argentina (+54)', 'CountryCode': '+54'},
  {'Name': 'armenia', 'Country': 'Armenia (+374)', 'CountryCode': '+374'},
  {'Name': 'aruba', 'Country': 'Aruba (+297)', 'CountryCode': '+297'},
  {'Name': 'australia', 'Country': 'Australia (+61)', 'CountryCode': '+61'},
  {'Name': 'austria', 'Country': 'Austria (+43)', 'CountryCode': '+43'},
  {'Name': 'azerbaijan', 'Country': 'Azerbaijan (+994)', 'CountryCode': '+994'},
  {'Name': 'bahamas', 'Country': 'Bahamas (+1-242)', 'CountryCode': '+1-242'},
  {'Name': 'bahrain', 'Country': 'Bahrain (+973)', 'CountryCode': '+973'},
  {'Name': 'bangladesh', 'Country': 'Bangladesh (+880)', 'CountryCode': '+880'},
  {'Name': 'barbados', 'Country': 'Barbados (+1-246)', 'CountryCode': '+1-246'},
  {'Name': 'belarus', 'Country': 'Belarus (+375)', 'CountryCode': '+375'},
  {'Name': 'belgium', 'Country': 'Belgium (+32)', 'CountryCode': '+32'},
  {'Name': 'belize', 'Country': 'Belize (+501)', 'CountryCode': '+501'},
  {'Name': 'benin', 'Country': 'Benin (+229)', 'CountryCode': '+229'},
  {'Name': 'bermuda', 'Country': 'Bermuda (+1-441)', 'CountryCode': '+1-441'},
  {'Name': 'bhutan', 'Country': 'Bhutan (+975)', 'CountryCode': '+975'},
  {'Name': 'bolivia', 'Country': 'Bolivia (+591)', 'CountryCode': '+591'},
  {'Name': 'bosnia-and-herzegovina', 'Country': 'Bosnia and Herzegovina (+387)', 'CountryCode': '+387'},
  {'Name': 'botswana', 'Country': 'Botswana (+267)', 'CountryCode': '+267'},
  {'Name': 'brazil', 'Country': 'Brazil (+55)', 'CountryCode': '+55'},
  {'Name': 'british-indian-ocean-territory', 'Country': 'British Indian Ocean Territory (+246)', 'CountryCode': '+246'},
  {'Name': 'british-virgin-islands', 'Country': 'British Virgin Islands (+1-284)', 'CountryCode': '+1-284'},
  {'Name': 'brunei', 'Country': 'Brunei (+673)', 'CountryCode': '+673'},
  {'Name': 'bulgaria', 'Country': 'Bulgaria (+359)', 'CountryCode': '+359'},
  {'Name': 'burkina-faso', 'Country': 'Burkina Faso (+226)', 'CountryCode': '+226'},
  {'Name': 'burundi', 'Country': 'Burundi (+257)', 'CountryCode': '+257'},
  {'Name': 'cambodia', 'Country': 'Cambodia (+855)', 'CountryCode': '+855'},
  {'Name': 'cameroon', 'Country': 'Cameroon (+237)', 'CountryCode': '+237'},
  {'Name': 'canada', 'Country': 'Canada (+1)', 'CountryCode': '+1'},
  {'Name': 'cape-verde', 'Country': 'Cape Verde (+238)', 'CountryCode': '+238'},
  {'Name': 'cayman-islands', 'Country': 'Cayman Islands (+1-345)', 'CountryCode': '+1-345'},
  {'Name': 'central-african-republic', 'Country': 'Central African Republic (+236)', 'CountryCode': '+236'},
  {'Name': 'chad', 'Country': 'Chad (+235)', 'CountryCode': '+235'},
  {'Name': 'chile', 'Country': 'Chile (+56)', 'CountryCode': '+56'},
  {'Name': 'china', 'Country': 'China (+86)', 'CountryCode': '+86'},
  {'Name': 'christmas-island', 'Country': 'Christmas Island (+61)', 'CountryCode': '+61'},
  {'Name': 'cocos-island', 'Country': 'Cocos Islands (+61)', 'CountryCode': '+61'},
  {'Name': 'colombia', 'Country': 'Colombia (+57)', 'CountryCode': '+57'},
  {'Name': 'comoros', 'Country': 'Comoros (+269)', 'CountryCode': '+269'},
  {'Name': 'cook-islands', 'Country': 'Cook Islands (+682)', 'CountryCode': '+682'},
  {'Name': 'costa-rica', 'Country': 'Costa Rica (+506)', 'CountryCode': '+506'},
  {'Name': 'croatia', 'Country': 'Croatia (+385)', 'CountryCode': '+385'},
  {'Name': 'cuba', 'Country': 'Cuba (+53)', 'CountryCode': '+53'},
  {'Name': 'curacao', 'Country': 'Curacao (+599)', 'CountryCode': '+599'},
  {'Name': 'cyprus', 'Country': 'Cyprus (+357)', 'CountryCode': '+357'},
  {'Name': 'czech-republic', 'Country': 'Czech Republic (+420)', 'CountryCode': '+420'},
  {'Name': 'democratic-republic-of-congo', 'Country': 'Democratic Republic of the Congo (+243)', 'CountryCode': '+243'},
  {'Name': 'denmark', 'Country': 'Denmark (+45)', 'CountryCode': '+45'},
  {'Name': 'djibouti', 'Country': 'Djibouti (+253)', 'CountryCode': '+253'},
  {'Name': 'dominica', 'Country': 'Dominica (+1-767)', 'CountryCode': '+1-767'},
  {'Name': 'dominican-republic', 'Country': 'Dominican Republic (+1-809, 1-829, 1-849)', 'CountryCode': '+1-809, 1-829, 1-849'},
  {'Name': 'east-timor', 'Country': 'East Timor (+670)', 'CountryCode': '670'},
  {'Name': 'ecuador', 'Country': 'Ecuador (+593)', 'CountryCode': '+593'},
  {'Name': 'egypt', 'Country': 'Egypt (+20)', 'CountryCode': '+20'},
  {'Name': 'el-salvador', 'Country': 'El Salvador (+503)', 'CountryCode': '+503'},
  {'Name': 'equatorial-guinea', 'Country': 'Equatorial Guinea (+240)', 'CountryCode': '+240'},
  {'Name': 'eritrea', 'Country': 'Eritrea (+291)', 'CountryCode': '+291'},
  {'Name': 'estonia', 'Country': 'Estonia (+372)', 'CountryCode': '+372'},
  {'Name': 'ethiopia', 'Country': 'Ethiopia (+251)', 'CountryCode': '+251'},
  {'Name': 'falkland-islands', 'Country': 'Falkland Islands (+500)', 'CountryCode': '+500'},
  {'Name': 'faroe-islands', 'Country': 'Faroe Islands (+298)', 'CountryCode': '+298'},
  {'Name': 'fiji', 'Country': 'Fiji (+679)', 'CountryCode': '+679'},
  {'Name': 'finland', 'Country': 'Finland (+358)', 'CountryCode': '+358'},
  {'Name': 'france', 'Country': 'France (+33)', 'CountryCode': '+33'},
  {'Name': 'french-polynesia', 'Country': 'French Polynesia (+689)', 'CountryCode': '+689'},
  {'Name': 'gabon', 'Country': 'Gabon (+241)', 'CountryCode': '+241'},
  {'Name': 'gambia', 'Country': 'Gambia (+220)', 'CountryCode': '+220'},
  {'Name': 'georgia', 'Country': 'Georgia (+995)', 'CountryCode': '+995'},
  {'Name': 'germany', 'Country': 'Germany (+49)', 'CountryCode': '+49'},
  {'Name': 'ghana', 'Country': 'Ghana (+233)', 'CountryCode': '+233'},
  {'Name': 'gibraltar', 'Country': 'Gibraltar (+350)', 'CountryCode': '+350'},
  {'Name': 'greece', 'Country': 'Greece (+30)', 'CountryCode': '+30'},
  {'Name': 'greenland', 'Country': 'Greenland (+299)', 'CountryCode': '+299'},
  {'Name': 'grenada', 'Country': 'Grenada (+1-473)', 'CountryCode': '+1-473'},
  {'Name': 'guam', 'Country': 'Guam (+1-671)', 'CountryCode': '+1-671'},
  {'Name': 'guatemala', 'Country': 'Guatemala (+502)', 'CountryCode': '+502'},
  {'Name': 'guernsey', 'Country': 'Guernsey (+44-1481)', 'CountryCode': '+44-1481'},
  {'Name': 'guinea', 'Country': 'Guinea (+224)', 'CountryCode': '+224'},
  {'Name': 'guinea-bissau', 'Country': 'Guinea-Bissau (+245)', 'CountryCode': '+245'},
  {'Name': 'guyana', 'Country': 'Guyana (+592)', 'CountryCode': '+592'},
  {'Name': 'haiti', 'Country': 'Haiti (+509)', 'CountryCode': '+509'},
  {'Name': 'honduras', 'Country': 'Honduras (+504)', 'CountryCode': '+504'},
  {'Name': 'hong-kong', 'Country': 'Hong Kong (+852)', 'CountryCode': '+852'},
  {'Name': 'hungary', 'Country': 'Hungary (+36)', 'CountryCode': '+36'},
  {'Name': 'iceland', 'Country': 'Iceland (+354)', 'CountryCode': '+354'},
  {'Name': 'india', 'Country': 'India (+91)', 'CountryCode': '+91'},
  {'Name': 'indonesia', 'Country': 'Indonesia (+62)', 'CountryCode': '+62'},
  {'Name': 'iran', 'Country': 'Iran (+98)', 'CountryCode': '+98'},
  {'Name': 'iraq', 'Country': 'Iraq (+964)', 'CountryCode': '+964'},
  {'Name': 'ireland', 'Country': 'Ireland (+353)', 'CountryCode': '+353'},
  {'Name': 'israel', 'Country': 'Israel (+972)', 'CountryCode': '+972'},
  {'Name': 'italy', 'Country': 'Italy (+39)', 'CountryCode': '+39'},
  {'Name': 'ivory-coast', 'Country': 'Ivory Coast (+225)', 'CountryCode': '+225'},
  {'Name': 'jamaica', 'Country': 'Jamaica (+1-876)', 'CountryCode': '+1-876'},
  {'Name': 'japan', 'Country': 'Japan (+81)', 'CountryCode': '+81'},
  {'Name': 'jersy', 'Country': 'Jersey (+44-1534)', 'CountryCode': '+44-1534'},
  {'Name': 'jordan', 'Country': 'Jordan (+962)', 'CountryCode': '+962'},
  {'Name': 'kazakhstan', 'Country': 'Kazakhstan (+7)', 'CountryCode': '+7'},
  {'Name': 'kenya', 'Country': 'Kenya (+254)', 'CountryCode': '+254'},
  {'Name': 'kosovo', 'Country': 'Kosovo (+383)', 'CountryCode': '+383'},
  {'Name': 'kuwait', 'Country': 'Kuwait (+965)', 'CountryCode': '+965'},
  {'Name': 'kyrgyzstan', 'Country': 'Kyrgyzstan (+996)', 'CountryCode': '+996'},
  {'Name': 'laos', 'Country': 'Laos (+856)', 'CountryCode': '+856'},
  {'Name': 'latvia', 'Country': 'Latvia (+371)', 'CountryCode': '+371'},
  {'Name': 'lebanon', 'Country': 'Lebanon (+961)', 'CountryCode': '+961'},
  {'Name': 'lesotho', 'Country': 'Lesotho (+266)', 'CountryCode': '+266'},
  {'Name': 'liberia', 'Country': 'Liberia (+231)', 'CountryCode': '+231'},
  {'Name': 'libya', 'Country': 'Libya (+218)', 'CountryCode': '+218'},
  {'Name': 'liechtenstein', 'Country': 'Liechtenstein (+423)', 'CountryCode': '+423'},
  {'Name': 'lithuania', 'Country': 'Lithuania (+370)', 'CountryCode': '+370'},
  {'Name': 'luxembourg', 'Country': 'Luxembourg (+352)', 'CountryCode': '+352'},
  {'Name': 'macao', 'Country': 'Macao (+853)', 'CountryCode': '+853'},
  {'Name': 'macedonia', 'Country': 'Macedonia (+389)', 'CountryCode': '+389'},
  {'Name': 'madagascar', 'Country': 'Madagascar (+261)', 'CountryCode': '+261'},
  {'Name': 'malawi', 'Country': 'Malawi (+265)', 'CountryCode': '+265'},
  {'Name': 'malaysia', 'Country': 'Malaysia (+60)', 'CountryCode': '+60'},
  {'Name': 'maldives', 'Country': 'Maldives (+960)', 'CountryCode': '+960'},
  {'Name': 'mali', 'Country': 'Mali (+223)', 'CountryCode': '+223'},
  {'Name': 'malta', 'Country': 'Malta (+356)', 'CountryCode': '+356'},
  {'Name': 'marshall-island', 'Country': 'Marshall Islands (+692)', 'CountryCode': '+692'},
  {'Name': 'mauritania', 'Country': 'Mauritania (+222)', 'CountryCode': '+222'},
  {'Name': 'mauritius', 'Country': 'Mauritius (+230)', 'CountryCode': '+230'},
  {'Name': 'mayotte', 'Country': 'Mayotte (+262)', 'CountryCode': '+262'},
  {'Name': 'mexico', 'Country': 'Mexico (+52)', 'CountryCode': '+52'},
  {'Name': 'micronesia', 'Country': 'Micronesia (+691)', 'CountryCode': '+691'},
  {'Name': 'moldova', 'Country': 'Moldova (+373)', 'CountryCode': '+373'},
  {'Name': 'monaco', 'Country': 'Monaco (+377)', 'CountryCode': '+377'},
  {'Name': 'mongolia', 'Country': 'Mongolia (+976)', 'CountryCode': '+976'},
  {'Name': 'montenegro', 'Country': 'Montenegro (+382)', 'CountryCode': '+382'},
  {'Name': 'montserrat', 'Country': 'Montserrat (+1-664)', 'CountryCode': '+1-664'},
  {'Name': 'morocco', 'Country': 'Morocco (+212)', 'CountryCode': '+212'},
  {'Name': 'mozambique', 'Country': 'Mozambique (+258)', 'CountryCode': '+258'},
  {'Name': 'myanmar', 'Country': 'Myanmar (+95)', 'CountryCode': '+95'},
  {'Name': 'namibia', 'Country': 'Namibia (+264)', 'CountryCode': '+264'},
  {'Name': 'nauru', 'Country': 'Nauru (+674)', 'CountryCode': '+674'},
  {'Name': 'nepal', 'Country': 'Nepal (+977)', 'CountryCode': '+977'},
  {'Name': 'netherlands', 'Country': 'Netherlands (+31)', 'CountryCode': '+31'},
  {'Name': 'new-caledonia', 'Country': 'New Caledonia (+687)', 'CountryCode': '+687'},
  {'Name': 'new-zealand', 'Country': 'New Zealand (+64)', 'CountryCode': '+64'},
  {'Name': 'nicaragua', 'Country': 'Nicaragua (+505)', 'CountryCode': '+505'},
  {'Name': 'niger', 'Country': 'Niger (+227)', 'CountryCode': '+227'},
  {'Name': 'nigeria', 'Country': 'Nigeria (+234)', 'CountryCode': '+234'},
  {'Name': 'niue', 'Country': 'Niue (+683)', 'CountryCode': '+683'},
  {'Name': 'north-korea', 'Country': 'North Korea (+850)', 'CountryCode': '+850'},
  {'Name': 'northern-marianas-islands', 'Country': 'Northern Mariana Islands (+1-670)', 'CountryCode': '+1-670'},
  {'Name': 'norway', 'Country': 'Norway (+47)', 'CountryCode': '+47'},
  {'Name': 'oman', 'Country': 'Oman (+968)', 'CountryCode': '+968'},
  {'Name': 'pakistan', 'Country': 'Pakistan (+92)', 'CountryCode': '+92'},
  {'Name': 'palau', 'Country': 'Palau (+680)', 'CountryCode': '+680'},
  {'Name': 'palestine', 'Country': 'Palestine (+970)', 'CountryCode': '+970'},
  {'Name': 'panama', 'Country': 'Panama (+507)', 'CountryCode': '+507'},
  {'Name': 'papua-new-guinea', 'Country': 'Papua New Guinea (+675)', 'CountryCode': '+675'},
  {'Name': 'paraguay', 'Country': 'Paraguay (+595)', 'CountryCode': '+595'},
  {'Name': 'peru', 'Country': 'Peru (+51)', 'CountryCode': '+51'},
  {'Name': 'philippines', 'Country': 'Philippines (+63)', 'CountryCode': '+63'},
  {'Name': 'pitcairn-islands', 'Country': 'Pitcairn (+64)', 'CountryCode': '+64'},
  {'Name': 'poland', 'Country': 'Poland (+48)', 'CountryCode': '+48'},
  {'Name': 'portugal', 'Country': 'Portugal (+351)', 'CountryCode': '+351'},
  {'Name': 'puerto-rico', 'Country': 'Puerto Rico (+1-787, 1-939)', 'CountryCode': '+1-787, 1-939'},
  {'Name': 'qatar', 'Country': 'Qatar (+974)', 'CountryCode': '+974'},
  {'Name': 'republic-of-the-congo', 'Country': 'Republic of the Congo (+242)', 'CountryCode': '+242'},
  {'Name': 'reunion', 'Country': 'Reunion (+262)', 'CountryCode': '+262'},
  {'Name': 'romania', 'Country': 'Romania (+40)', 'CountryCode': '+40'},
  {'Name': 'russia', 'Country': 'Russia (+7)', 'CountryCode': '+7'},
  {'Name': 'rwanda', 'Country': 'Rwanda (+250)', 'CountryCode': '+250'},
  {'Name': 'saint-kitts-and-nevis', 'Country': 'Saint Kitts and Nevis (+1-869)', 'CountryCode': '+1-869'},
  {'Name': 'saint-lucia', 'Country': 'Saint Lucia (+1-758)', 'CountryCode': '+1-758'},
  {'Name': 'saint-pierre-and-miquelon', 'Country': 'Saint Pierre and Miquelon (+508)', 'CountryCode': '+508'},
  {'Name': 'saint-vincent-and-the-grenadines', 'Country': 'Saint Vincent and the Grenadines (+1-784)', 'CountryCode': '+1-784'},
  {'Name': 'samoa', 'Country': 'Samoa (+685)', 'CountryCode': '+685'},
  {'Name': 'san-marino', 'Country': 'San Marino (+378)', 'CountryCode': '+378'},
  {'Name': 'sao-tome-and-principe', 'Country': 'Sao Tome and Principe (+239)', 'CountryCode': '+239'},
  {'Name': 'saudi-arabia', 'Country': 'Saudi Arabia (+966)', 'CountryCode': '+966'},
  {'Name': 'senegal', 'Country': 'Senegal (+221)', 'CountryCode': '+221'},
  {'Name': 'serbia', 'Country': 'Serbia (+381)', 'CountryCode': '+381'},
  {'Name': 'seychelles', 'Country': 'Seychelles (+248)', 'CountryCode': '+248'},
  {'Name': 'sierra-leone', 'Country': 'Sierra Leone (+232)', 'CountryCode': '+232'},
  {'Name': 'singapore', 'Country': 'Singapore (+65)', 'CountryCode': '+65'},
  {'Name': 'sint-maarten', 'Country': 'Sint Maarten (+1-721)', 'CountryCode': '+1-721'},
  {'Name': 'slovakia', 'Country': 'Slovakia (+421)', 'CountryCode': '+421'},
  {'Name': 'slovenia', 'Country': 'Slovenia (+386)', 'CountryCode': '+386'},
  {'Name': 'solomon-islands', 'Country': 'Solomon Islands (+677)', 'CountryCode': '+677'},
  {'Name': 'somalia', 'Country': 'Somalia (+252)', 'CountryCode': '+252'},
  {'Name': 'south-africa', 'Country': 'South Africa (+27)', 'CountryCode': '+27'},
  {'Name': 'south-korea', 'Country': 'South Korea (+82)', 'CountryCode': '+82'},
  {'Name': 'south-sudan', 'Country': 'South Sudan (+211)', 'CountryCode': '+211'},
  {'Name': 'spain', 'Country': 'Spain (+34)', 'CountryCode': '+34'},
  {'Name': 'sri-lanka', 'Country': 'Sri Lanka (+94)', 'CountryCode': '+94'},
  {'Name': 'sudan', 'Country': 'Sudan (+249)', 'CountryCode': '+249'},
  {'Name': 'suriname', 'Country': 'Suriname (+597)', 'CountryCode': '+597'},
  {'Name': 'swaziland', 'Country': 'Swaziland (+268)', 'CountryCode': '+268'},
  {'Name': 'sweden', 'Country': 'Sweden (+46)', 'CountryCode': '+46'},
  {'Name': 'switzerland', 'Country': 'Switzerland (+41)', 'CountryCode': '+41'},
  {'Name': 'syria', 'Country': 'Syria (+963)', 'CountryCode': '+963'},
  {'Name': 'taiwan', 'Country': 'Taiwan (+886)', 'CountryCode': '+886'},
  {'Name': 'tajikistan', 'Country': 'Tajikistan (+992)', 'CountryCode': '+992'},
  {'Name': 'tanzania', 'Country': 'Tanzania (+255)', 'CountryCode': '+255'},
  {'Name': 'thailand', 'Country': 'Thailand (+66)', 'CountryCode': '+66'},
  {'Name': 'togo', 'Country': 'Togo (+228)', 'CountryCode': '+228'},
  {'Name': 'tokelau', 'Country': 'Tokelau (+690)', 'CountryCode': '+690'},
  {'Name': 'tonga', 'Country': 'Tonga (+676)', 'CountryCode': '+676'},
  {'Name': 'trinidad-and-tobago', 'Country': 'Trinidad and Tobago (+1-868)', 'CountryCode': '+1-868'},
  {'Name': 'tunisia', 'Country': 'Tunisia (+216)', 'CountryCode': '+216'},
  {'Name': 'turkey', 'Country': 'Turkey (+90)', 'CountryCode': '+90'},
  {'Name': 'turkmenistan', 'Country': 'Turkmenistan (+993)', 'CountryCode': '+993'},
  {'Name': 'turks-and-caicos', 'Country': 'Turks and Caicos Islands (1-649)', 'CountryCode': '1-649'},
  {'Name': 'tuvalu', 'Country': 'Tuvalu (+688)', 'CountryCode': '+688'},
  {'Name': 'uganda', 'Country': 'Uganda (+256)', 'CountryCode': '+256'},
  {'Name': 'ukraine', 'Country': 'Ukraine (+380)', 'CountryCode': '+380'},
  {'Name': 'united-arab-emirates', 'Country': 'United Arab Emirates (+971)', 'CountryCode': '+971'},
  {'Name': 'united-kindom', 'Country': 'United Kingdom (+44)', 'CountryCode': '+44'},
  {'Name': 'united-states-of-america', 'Country': 'United States of America (+1)', 'CountryCode': '+1'},
  {'Name': 'uruguay', 'Country': 'Uruguay (+598)', 'CountryCode': '+598'},
  {'Name': 'uzbekistan', 'Country': 'Uzbekistan (+998)', 'CountryCode': '+998'},
  {'Name': 'vanautu', 'Country': 'Vanuatu (+678)', 'CountryCode': '+678'},
  {'Name': 'vatican-city', 'Country': 'Vatican City (+379)', 'CountryCode': '+379'},
  {'Name': 'venezuela', 'Country': 'Venezuela (+58)', 'CountryCode': '+58'},
  {'Name': 'vietnam', 'Country': 'Vietnam (+84)', 'CountryCode': '+84'},
  {'Name': 'wallis-and-futuna', 'Country': 'Wallis and Futuna (+681)', 'CountryCode': '+681'},
  {'Name': 'western-sahara', 'Country': 'Western Sahara (+212)', 'CountryCode': '+212'},
  {'Name': 'yemen', 'Country': 'Yemen (+967)', 'CountryCode': '+967'},
  {'Name': 'zambia', 'Country': 'Zambia (+260)', 'CountryCode': '+260'},
  {'Name': 'zimbabwe', 'Country': 'Zimbabwe (+236)', 'CountryCode': '+236'}
]
